//! The PKI directory (doc/connectors/opcua-connector-spec.md §4): its layout, the application
//! instance certificate, and the file operations `tedge-dot pki` performs.
//!
//! Trust decisions are not made here: they belong to the patched certificate store
//! (`opcua::crypto::trust_list`), which reads the same directories on every validation.
//!
//! Every file this module writes is written atomically (a temporary file in the same directory,
//! then `rename`), and certificate generation runs under an exclusive lock on `own/.lock`, so
//! several connectors sharing one PKI directory neither read a partial file nor generate two
//! certificates.

use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use tracing::warn;

use opcua::crypto::trust_list::{
    parse_certificates, parse_crls, ISSUER_CERTS_DIR, ISSUER_CRL_DIR, REJECTED_CERTS_DIR,
    TRUSTED_CERTS_DIR, TRUSTED_CRL_DIR,
};
use opcua::crypto::{PrivateKey, X509Data, OWN_CERTIFICATE_PATH, OWN_PRIVATE_KEY_PATH, X509};

use crate::config::{check_private_key_mode, resolve_path, OpcuaConnection};

/// Validity of a generated application certificate (OPC UA Part 12 recommends at most 5 years).
pub const DEFAULT_CERTIFICATE_DAYS: u32 = 5 * 365;
/// Key size of a generated application certificate.
pub const DEFAULT_KEY_BITS: u32 = 2048;
/// Warn about the application certificate this long before it expires.
pub const EXPIRY_WARNING_DAYS: i64 = 30;

/// The subdirectories of a PKI directory, in creation order.
pub const LAYOUT: [&str; 7] = [
    "own/certs",
    "own/private",
    TRUSTED_CERTS_DIR,
    TRUSTED_CRL_DIR,
    ISSUER_CERTS_DIR,
    ISSUER_CRL_DIR,
    REJECTED_CERTS_DIR,
];

/// Which certificate group a stored certificate belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Group {
    Trusted,
    Issuers,
    Rejected,
}

impl Group {
    pub const ALL: [Group; 3] = [Group::Trusted, Group::Issuers, Group::Rejected];

    pub fn name(self) -> &'static str {
        match self {
            Group::Trusted => "trusted",
            Group::Issuers => "issuers",
            Group::Rejected => "rejected",
        }
    }

    pub fn parse(s: &str) -> Option<Group> {
        Group::ALL.into_iter().find(|g| g.name() == s)
    }

    fn certs_dir(self) -> &'static str {
        match self {
            Group::Trusted => TRUSTED_CERTS_DIR,
            Group::Issuers => ISSUER_CERTS_DIR,
            Group::Rejected => REJECTED_CERTS_DIR,
        }
    }

    fn crl_dir(self) -> Option<&'static str> {
        match self {
            Group::Trusted => Some(TRUSTED_CRL_DIR),
            Group::Issuers => Some(ISSUER_CRL_DIR),
            Group::Rejected => None,
        }
    }
}

/// A PKI directory.
#[derive(Debug, Clone)]
pub struct Pki {
    root: PathBuf,
}

/// A loaded application instance certificate.
#[derive(Clone)]
pub struct OwnCertificate {
    pub certificate: X509,
    pub private_key: PrivateKey,
    pub certificate_path: PathBuf,
    pub private_key_path: PathBuf,
    /// Generated by this call (rather than read).
    pub generated: bool,
}

/// One certificate file in a group.
#[derive(Debug, Clone)]
pub struct CertEntry {
    pub group: Group,
    pub path: PathBuf,
    pub der: Vec<u8>,
    pub thumbprint: String,
    pub subject: String,
    pub not_after: Option<String>,
    pub is_ca: bool,
    /// For a CA: whether a CRL it issued is present in its group's `crl` directory.
    pub has_crl: Option<bool>,
}

/// What [`Pki::create`] should put into a generated certificate.
#[derive(Debug, Clone)]
pub struct CertificateRequest {
    pub application_name: String,
    pub application_uri: String,
    /// DNS names and IP addresses; the machine's host name when empty.
    pub hostnames: Vec<String>,
    pub days: u32,
}

impl CertificateRequest {
    pub fn for_connection(conn: &OpcuaConnection) -> CertificateRequest {
        CertificateRequest {
            application_name: conn.application_name.clone(),
            application_uri: conn.application_uri.clone(),
            hostnames: Vec::new(),
            days: DEFAULT_CERTIFICATE_DAYS,
        }
    }
}

impl Pki {
    pub fn new(root: impl Into<PathBuf>) -> Pki {
        Pki { root: root.into() }
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Create every missing subdirectory; `own/private` is made owner-only.
    pub fn ensure_layout(&self) -> Result<(), String> {
        for sub in LAYOUT {
            let dir = self.root.join(sub);
            fs::create_dir_all(&dir)
                .map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
        }
        set_mode(&self.root.join("own/private"), 0o700)?;
        Ok(())
    }

    pub fn default_certificate_path(&self) -> PathBuf {
        self.root.join(OWN_CERTIFICATE_PATH)
    }

    pub fn default_private_key_path(&self) -> PathBuf {
        self.root.join(OWN_PRIVATE_KEY_PATH)
    }

    /// The certificate and key paths a connection uses: its `certificate`/`private_key` when
    /// both are set, the PKI directory's `own/` entries otherwise.
    pub fn own_paths(&self, conn: &OpcuaConnection, base_dir: Option<&Path>) -> (PathBuf, PathBuf) {
        match (&conn.certificate, &conn.private_key) {
            (Some(cert), Some(key)) => (resolve_path(base_dir, cert), resolve_path(base_dir, key)),
            _ => (
                self.default_certificate_path(),
                self.default_private_key_path(),
            ),
        }
    }

    /// Read the application certificate, generating it first when it is missing and the
    /// connection allows that. The certificate must carry `application_uri` as a URI SAN and
    /// match its key, and the key must be private to its owner.
    pub fn load_or_create_own(
        &self,
        conn: &OpcuaConnection,
        base_dir: Option<&Path>,
    ) -> Result<OwnCertificate, String> {
        let explicit = conn.certificate.is_some() || conn.private_key.is_some();
        if explicit && (conn.certificate.is_none() || conn.private_key.is_none()) {
            return Err("certificate and private_key must be set together".into());
        }
        let (cert_path, key_path) = self.own_paths(conn, base_dir);
        if explicit {
            let own = read_own(&cert_path, &key_path)?;
            check_uri(&own.certificate, &conn.application_uri)?;
            return Ok(own);
        }

        // Check-and-generate under the lock, so two connectors starting together agree.
        self.ensure_layout()?;
        let _lock = self.lock_own()?;
        // The key is written first, so a key without a certificate is an interrupted
        // generation: set it aside and generate again rather than fail every start.
        if conn.create_certificate && key_path.exists() && !cert_path.exists() {
            let kept = move_aside(&[&key_path])?;
            warn!(
                "{} has no certificate (interrupted generation?); moved it to {} and generating a new certificate",
                key_path.display(),
                kept.join(", ")
            );
        }
        let generated = if cert_path.exists() || key_path.exists() {
            if !key_path.exists() {
                return Err(format!(
                    "{} has no private key at {}; restore the key or remove the certificate to generate a new one",
                    cert_path.display(),
                    key_path.display()
                ));
            }
            false
        } else if conn.create_certificate {
            self.write_new_own(&CertificateRequest::for_connection(conn))?;
            true
        } else {
            return Err(format!(
                "no certificate at {} and create_certificate is false",
                cert_path.display()
            ));
        };
        let mut own = read_own(&cert_path, &key_path)?;
        own.generated = generated;
        check_uri(&own.certificate, &conn.application_uri)?;
        Ok(own)
    }

    /// Generate the application certificate (`tedge-dot pki create`). An existing one is
    /// refused unless `force`, which keeps it under `own/` with a timestamp suffix.
    pub fn create(
        &self,
        request: &CertificateRequest,
        force: bool,
    ) -> Result<OwnCertificate, String> {
        self.ensure_layout()?;
        let _lock = self.lock_own()?;
        let cert_path = self.default_certificate_path();
        let key_path = self.default_private_key_path();
        if cert_path.exists() || key_path.exists() {
            if !force {
                return Err(format!(
                    "an application certificate already exists at {} (use --force to replace it)",
                    cert_path.display()
                ));
            }
            move_aside(&[&cert_path, &key_path])?;
        }
        self.write_new_own(request)?;
        let mut own = read_own(&cert_path, &key_path)?;
        own.generated = true;
        Ok(own)
    }

    fn write_new_own(&self, request: &CertificateRequest) -> Result<(), String> {
        let (cert, key) = generate(request)?;
        let der = cert
            .to_der()
            .map_err(|_| "cannot encode the certificate".to_string())?;
        let pem = key
            .to_pem()
            .map_err(|e| format!("cannot encode the private key: {e}"))?;
        // Key first: a certificate without its key is never visible.
        write_atomic(&self.default_private_key_path(), pem.as_bytes(), 0o600)?;
        write_atomic(&self.default_certificate_path(), &der, 0o644)?;
        Ok(())
    }

    fn lock_own(&self) -> Result<File, String> {
        let path = self.root.join("own/.lock");
        let file = OpenOptions::new()
            .create(true)
            .truncate(false)
            .write(true)
            .open(&path)
            .map_err(|e| format!("cannot open {}: {e}", path.display()))?;
        file.lock()
            .map_err(|e| format!("cannot lock {}: {e}", path.display()))?;
        Ok(file)
    }

    /// Every certificate in `group`, sorted by file name.
    pub fn list(&self, group: Group) -> Vec<CertEntry> {
        let dir = self.root.join(group.certs_dir());
        let crls: Vec<Vec<u8>> = group
            .crl_dir()
            .map(|d| read_all(&self.root.join(d), parse_crls))
            .unwrap_or_default();
        let mut out = Vec::new();
        for path in files(&dir) {
            let Ok(bytes) = fs::read(&path) else { continue };
            for der in parse_certificates(&bytes) {
                let Ok(cert) = X509::from_der(&der) else {
                    continue;
                };
                let is_ca = cert.is_ca();
                let has_crl = is_ca.then(|| crls.iter().any(|crl| crl_issuer_matches(crl, &cert)));
                out.push(CertEntry {
                    group,
                    path: path.clone(),
                    thumbprint: thumbprint(&der),
                    subject: cert.subject_text(),
                    not_after: cert.not_after().ok().map(|t| timestamp(&t)),
                    is_ca,
                    has_crl,
                    der,
                });
            }
        }
        out
    }

    /// The single certificate in `groups` whose thumbprint starts with `prefix` (at least 8 hex
    /// digits, any case). `Err(Ambiguous)` lists every match.
    pub fn find(&self, prefix: &str, groups: &[Group]) -> Result<CertEntry, FindError> {
        let prefix = prefix.to_ascii_lowercase();
        if prefix.len() < 8 || !prefix.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(FindError::BadPrefix);
        }
        let mut matches: Vec<CertEntry> = groups
            .iter()
            .flat_map(|g| self.list(*g))
            .filter(|e| e.thumbprint.starts_with(&prefix))
            .collect();
        // One certificate stored twice in a group (two files) is still one certificate.
        matches.dedup_by(|a, b| a.group == b.group && a.der == b.der);
        match matches.len() {
            0 => Err(FindError::NotFound),
            1 => Ok(matches.remove(0)),
            _ => Err(FindError::Ambiguous(matches)),
        }
    }

    /// Store a certificate in `group` under its canonical name.
    pub fn store(&self, group: Group, der: &[u8]) -> Result<PathBuf, String> {
        let cert = X509::from_der(der).map_err(|_| "not a certificate".to_string())?;
        let path = self
            .root
            .join(group.certs_dir())
            .join(canonical_name(&cert, der));
        write_atomic(&path, der, 0o644)?;
        Ok(path)
    }

    /// Move a stored certificate into another group (removing every copy from its old group).
    pub fn relocate(&self, entry: &CertEntry, to: Group) -> Result<PathBuf, String> {
        let path = self.store(to, &entry.der)?;
        self.remove(entry)?;
        Ok(path)
    }

    /// Take the entry's certificate out of every file of its group that holds it. Other
    /// certificates of a PEM bundle stay: only the file's matching blocks are dropped, and a
    /// file is deleted only when no certificate would be left in it.
    pub fn remove(&self, entry: &CertEntry) -> Result<(), String> {
        let mut done: Vec<PathBuf> = Vec::new();
        for other in self.list(entry.group) {
            if other.der == entry.der && !done.contains(&other.path) {
                remove_from_file(&other.path, &entry.der)?;
                done.push(other.path);
            }
        }
        Ok(())
    }

    /// Store a CRL next to the CA that issued it (trusted or issuers).
    pub fn add_crl(&self, der: &[u8]) -> Result<PathBuf, String> {
        for group in [Group::Trusted, Group::Issuers] {
            for ca in self.list(group).into_iter().filter(|e| e.is_ca) {
                let cert = X509::from_der(&ca.der).map_err(|_| "unreadable CA".to_string())?;
                if crl_issuer_matches(der, &cert) {
                    let dir = self.root.join(group.crl_dir().unwrap_or_default());
                    let path = dir.join(format!("{}.crl", thumbprint(der)));
                    write_atomic(&path, der, 0o644)?;
                    return Ok(path);
                }
            }
        }
        Err("the CRL was not issued by any CA in trusted/ or issuers/".into())
    }
}

/// Rename the existing files among `paths` to `<name>.<unix time>`; returns the new names.
fn move_aside(paths: &[&Path]) -> Result<Vec<String>, String> {
    let stamp = time::OffsetDateTime::now_utc().unix_timestamp();
    let mut kept = Vec::new();
    for path in paths.iter().filter(|p| p.exists()) {
        let backup = path.with_file_name(format!(
            "{}.{stamp}",
            path.file_name().unwrap_or_default().to_string_lossy()
        ));
        fs::rename(path, &backup)
            .map_err(|e| format!("cannot move {} aside: {e}", path.display()))?;
        kept.push(backup.display().to_string());
    }
    Ok(kept)
}

/// See [`Pki::remove`]. Mirrors `remove_from_file` in the C build's `ua_pki.c`.
fn remove_from_file(path: &Path, der: &[u8]) -> Result<(), String> {
    let bytes = match fs::read(path) {
        Ok(bytes) => bytes,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(format!("cannot read {}: {e}", path.display())),
    };
    let certs = parse_certificates(&bytes);
    let keep = certs.iter().filter(|c| c.as_slice() != der).count();
    if certs.is_empty() || keep == certs.len() {
        return Ok(());
    }
    if keep == 0 {
        return match fs::remove_file(path) {
            Err(e) if e.kind() != std::io::ErrorKind::NotFound => {
                Err(format!("cannot remove {}: {e}", path.display()))
            }
            _ => Ok(()),
        };
    }
    // A bundle (PEM text, since a DER file holds one certificate): drop the matching blocks.
    const BEGIN: &str = "-----BEGIN CERTIFICATE-----";
    const END: &str = "-----END CERTIFICATE-----";
    let text = String::from_utf8_lossy(&bytes);
    let mut out = String::with_capacity(text.len());
    let mut rest: &str = &text;
    while let Some(b) = rest.find(BEGIN) {
        let Some(e) = rest[b..].find(END).map(|e| b + e + END.len()) else { break };
        let block = &rest[b..e];
        if matches!(parse_certificates(block.as_bytes()).as_slice(), [one] if one == der) {
            out.push_str(&rest[..b]);
            let after = &rest[e..];
            let after = after.strip_prefix('\r').unwrap_or(after);
            rest = after.strip_prefix('\n').unwrap_or(after);
        } else {
            out.push_str(&rest[..e]);
            rest = &rest[e..];
        }
    }
    out.push_str(rest);
    let mode = fs::metadata(path)
        .map(|m| std::os::unix::fs::PermissionsExt::mode(&m.permissions()) & 0o7777)
        .unwrap_or(0o644);
    write_atomic(path, out.as_bytes(), mode)
}

/// Why [`Pki::find`] found nothing usable.
#[derive(Debug)]
pub enum FindError {
    BadPrefix,
    NotFound,
    Ambiguous(Vec<CertEntry>),
}

/// Whether a DER CRL names `ca` as its issuer and carries a valid signature by it.
fn crl_issuer_matches(crl: &[u8], ca: &X509) -> bool {
    ca.to_der()
        .is_ok_and(|ca| opcua::crypto::trust_list::crl_is_issued_by(crl, &ca))
}

fn read_own(cert_path: &Path, key_path: &Path) -> Result<OwnCertificate, String> {
    let bytes = fs::read(cert_path)
        .map_err(|e| format!("cannot read certificate {}: {e}", cert_path.display()))?;
    let certificate = parse_certificates(&bytes)
        .first()
        .and_then(|der| X509::from_der(der).ok())
        .ok_or_else(|| format!("{} is not a certificate", cert_path.display()))?;
    check_private_key_mode(key_path, "private_key")?;
    let private_key = PrivateKey::read_pem_file(key_path)
        .map_err(|_| format!("cannot read private key {}", key_path.display()))?;
    if !certificate.matches_private_key(&private_key) {
        return Err(format!(
            "private key {} does not belong to certificate {}",
            key_path.display(),
            cert_path.display()
        ));
    }
    Ok(OwnCertificate {
        certificate,
        private_key,
        certificate_path: cert_path.to_path_buf(),
        private_key_path: key_path.to_path_buf(),
        generated: false,
    })
}

fn check_uri(cert: &X509, application_uri: &str) -> Result<(), String> {
    let names = cert.alternate_names();
    if names.iter().any(|n| n == application_uri) {
        return Ok(());
    }
    let uri = names
        .iter()
        .find(|n| n.contains(':') && !n.parse::<std::net::IpAddr>().is_ok())
        .map(String::as_str)
        .unwrap_or("none");
    Err(format!(
        "the certificate's application URI ({uri}) does not match application_uri ({application_uri})"
    ))
}

fn generate(request: &CertificateRequest) -> Result<(X509, PrivateKey), String> {
    // The URI first: that is where OPC UA stacks look for the application URI.
    let names = X509Data::alt_host_names(
        &request.application_uri,
        Some(request.hostnames.clone()),
        false,
        request.hostnames.is_empty(),
        false,
    );
    let data = X509Data {
        key_size: DEFAULT_KEY_BITS,
        common_name: request.application_name.clone(),
        organization: request.application_name.clone(),
        organizational_unit: String::new(),
        country: String::new(),
        state: String::new(),
        alt_host_names: names,
        certificate_duration_days: request.days,
    };
    X509::cert_and_pkey(&data)
}

/// A certificate time as `YYYY-MM-DDTHH:MM:SSZ` (the form both builds print).
pub fn timestamp(t: &chrono::DateTime<chrono::Utc>) -> String {
    t.format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// The SHA-1 thumbprint of a DER blob in lower-case hex.
pub fn thumbprint(der: &[u8]) -> String {
    use sha1::{Digest, Sha1};
    Sha1::digest(der)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// `<CN>_<thumbprint>.der`, the name tedge-dot stores certificates under.
pub fn canonical_name(cert: &X509, der: &[u8]) -> String {
    let cn: String = cert
        .common_name_value()
        .unwrap_or_default()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("{cn}_{}.der", thumbprint(der))
}

/// Write `bytes` to `path` through a temporary file in the same directory and a rename.
pub fn write_atomic(path: &Path, bytes: &[u8], mode: u32) -> Result<(), String> {
    let dir = path.parent().unwrap_or(Path::new("."));
    fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    let name = path.file_name().unwrap_or_default().to_string_lossy();
    // A fresh temporary file: never an existing file or a symlink someone placed at the name
    // (O_EXCL | O_NOFOLLOW), and its mode set through the descriptor, not the path.
    let (tmp, mut file) = (0..16)
        .find_map(|attempt| {
            let tmp = dir.join(format!(".{name}.{}.{}.tmp", std::process::id(), temp_suffix(attempt)));
            let mut options = OpenOptions::new();
            options.write(true).create_new(true);
            #[cfg(unix)]
            {
                use std::os::unix::fs::OpenOptionsExt;
                options.mode(mode).custom_flags(libc::O_NOFOLLOW);
            }
            match options.open(&tmp) {
                Ok(file) => Some(Ok((tmp, file))),
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => None,
                Err(e) => Some(Err(format!("cannot write {}: {e}", path.display()))),
            }
        })
        .unwrap_or_else(|| Err(format!("cannot write {}: no free temporary name", path.display())))?;
    let result = (|| {
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            file.set_permissions(fs::Permissions::from_mode(mode))?;
        }
        file.write_all(bytes)?;
        file.sync_all()?;
        drop(file);
        // rename(2) replaces a symlink at `path` itself, never its target.
        fs::rename(&tmp, path)
    })();
    if let Err(e) = result {
        let _ = fs::remove_file(&tmp);
        return Err(format!("cannot write {}: {e}", path.display()));
    }
    Ok(())
}

fn temp_suffix(attempt: u32) -> u64 {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    (u64::from(nanos) << 8) | u64::from(attempt)
}

fn set_mode(path: &Path, mode: u32) -> Result<(), String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(mode))
            .map_err(|e| format!("cannot set permissions of {}: {e}", path.display()))?;
    }
    #[cfg(not(unix))]
    let _ = (path, mode);
    Ok(())
}

fn files(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file())
        .filter(|p| {
            !p.file_name()
                .is_some_and(|n| n.to_string_lossy().starts_with('.'))
        })
        .collect();
    files.sort();
    files
}

fn read_all(dir: &Path, parse: fn(&[u8]) -> Vec<Vec<u8>>) -> Vec<Vec<u8>> {
    files(dir)
        .into_iter()
        .filter_map(|p| fs::read(p).ok())
        .flat_map(|b| parse(&b))
        .collect()
}
